### ISSUE TITLE
Empty SMS window after adding Google account in Gnome Online Accounts

### ISSUE THREAD

**Issue by linuxundich** [andyholmes/gnome-shell-extension-mconnect#10] opened 2017-08-11 08:15 UTC
I installed your extension on a up to date arch system. Everything worked fine at first, but I wanted to have "Send SMS messages with optional Google Contacts auto-completion". So i added my google account to the gnome online accounts. After this this the SMS window stays empty, even after restarting the whole system.

![empty-sms-window](https://user-images.githubusercontent.com/1716643/29205569-fa3a8b64-7e7d-11e7-858b-4fdab89ce8c0.png)

//Edit: It might be connected to missing dependencies, but I'm not sure what the arch equivalent to the debian packages gir1.2-goa-1.0 and gir-gdata-0.0 might be.

**Comment by andyholmes** [comment] 2017-08-11 08:32
@linuxundich I believe I have fixed this in the latest Release v4. The dialog shoudn't choke at all anymore, but to get Google Contacts working you'll have to install GIR for both Gnome Online Accounts and GData. On Ubuntu these are called "gir1.2-goa-1.0" and "gir-gdata-0.0". They should be named something similar in Arch.

**Comment by andyholmes** [comment] 2017-08-11 08:38
Duplicate of #3

**Comment by linuxundich** [comment] 2017-08-11 08:41
Hi Andy, I already run v4:

```
$ grep version ~/.local/share/gnome-shell/extensions/mconnect@andyholmes.github.io/metadata.json
"version": "4",
"shell-version": [ "3.24", "3.24.1", "3.24.2" ],

```

About those packages: I think these components are already included in the [gnome-online-accounts](https://www.archlinux.org/packages/extra/i686/gnome-online-accounts/) package of arch and there are no extra packages needed.

**Comment by andyholmes** [comment] 2017-08-11 08:45
@linuxundich I'm having trouble reproducing this, although you certainly aren't the only person to report it. Could please follow these steps in a terminal and report any messages you receive:

    cd ~/.local/share/gnome-shell/extensions/mconnect@andyholmes.github.io
    # lists devices in the format "<device-name>: <device-id>"
    gjs share.js -l
    gjs sms.js --device=<device-id>

**Comment by linuxundich** [comment] 2017-08-11 08:51
Sure, here we go...
```
$ cd ~/.local/share/gnome-shell/extensions/mconnect@andyholmes.github.io
$ gjs share.js -l
lge: b0dca1ab681e5386
$ gjs sms.js --device=b0dca1ab681e5386
$ 
```
After the last command the empty SMS window opens and there are no messages. I closed that window and tried it a second time. This time the SMS window didn't open at all and I geht these messages.

```
$ gjs sms.js --device=b0dca1ab681e5386

(MConnect SMS:7474): Gjs-WARNING **: JS ERROR: TypeError: phoneNumber.uri is null
ContactCompletion<._populate@sms.js:252:21
wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22
ContactCompletion<._init@sms.js:231:17
wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22
ContactEntry<._init@sms.js:343:25
wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22
ApplicationWindow<._init@sms.js:414:29
wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22
Application<.vfunc_activate@sms.js:665:33
wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22
@sms.js:688:2
```

The journal outputs the following...

```
Aug 11 10:50:00 ontario kdeconnectd.desktop[1348]: kdeconnect.core: Socket connected
Aug 11 10:50:00 ontario kdeconnectd.desktop[1348]: kdeconnect.core: TCP connection done (i'm the existing device)
Aug 11 10:50:00 ontario kdeconnectd.desktop[1348]: kdeconnect.core: Starting server ssl (I'm the client TCP socket)
Aug 11 10:50:01 ontario kdeconnectd.desktop[1348]: kdeconnect.core: Socket connected
Aug 11 10:50:01 ontario kdeconnectd.desktop[1348]: kdeconnect.core: TCP connection done (i'm the existing device)
Aug 11 10:50:01 ontario kdeconnectd.desktop[1348]: kdeconnect.core: Starting server ssl (I'm the client TCP socket)
Aug 11 10:50:01 ontario kdeconnectd.desktop[1348]: kdeconnect.core: Socket succesfully stablished an SSL connection
Aug 11 10:50:01 ontario kdeconnectd.desktop[1348]: kdeconnect.core: Socket connected
Aug 11 10:50:01 ontario kdeconnectd.desktop[1348]: kdeconnect.core: TCP connection done (i'm the existing device)
Aug 11 10:50:01 ontario kdeconnectd.desktop[1348]: kdeconnect.core: Starting server ssl (I'm the client TCP socket)
Aug 11 10:50:01 ontario kdeconnectd.desktop[1348]: kdeconnect.core: Socket succesfully stablished an SSL connection
Aug 11 10:50:01 ontario kdeconnectd.desktop[1348]: kdeconnect.core: Socket succesfully stablished an SSL connection
Aug 11 10:50:08 ontario kdeconnectd.desktop[1348]: kdeconnect.plugin.notification: Not found noti by internal Id:  "0|com.google.android.apps.maps|121542904|null|10211"
```

**Comment by andyholmes** [comment] 2017-08-11 09:00
Ok, I think I have fixed it this time. If this ZIP works it will be v5, so no need to upgrade if it does.
[mconnect@andyholmes.github.io.zip](https://github.com/andyholmes/gnome-shell-extension-mconnect/files/1217352/mconnect.andyholmes.github.io.zip)

**Comment by linuxundich** [comment] 2017-08-11 09:20
Hi Andy, thanks! It works now...

![kde-connect-adressen](https://user-images.githubusercontent.com/1716643/29207597-0b8e730e-7e87-11e7-8132-258121e45ac5.png)

**Comment by andyholmes** [comment] 2017-08-11 09:22
Awesome, thanks for working through this with me.

**Closed** 2017-08-11 09:32 UTC
Labels: duplicate
