### ISSUE TITLE
[DISCUSSION] "Service Indicator"/"Device Indicator" Icons and Behaviour

### ISSUE THREAD

**Issue by isantop** [andyholmes/gnome-shell-extension-mconnect#19] opened 2017-08-14 22:30 UTC
Using extension version 7.

When I have a phone set up on my system, I have two identical phone icons in the top panel. This is a bit redundant and looks weird, especially since the icons aren't the same size:

![screenshot from 2017-08-14 16-27-30](https://user-images.githubusercontent.com/5883565/29294627-80c0287e-810d-11e7-86d9-398a7d0fa4f6.png)

It would be nice to hide the System Menu item when there is a device paired and active, or when there are no devices found. Or even at minimum an option in the settings to hide it. 

Otherwise I love this extension! Much better than the old indicator-kdeconnect solution. Keep up the good work!

**Comment by andyholmes** [comment] 2017-08-14 22:44
This was brought up in another bug where I said:

> In regards to having two icons, the "system indicator" icon is there to be consistent with Gnome Shell indicating that a particular service is active, such as Location Service in your screenshot, while the individual icons will differ depending on the device type (currently smartphone, tablet or laptop).

Although I can see it could be confusing or distracting if there are fewer icons in the tray between the two icons. Currently the system icon will not display if the service isn't started (KDE Connect/MConnnect). I could add an option to always hide the icon, use a different icon that implied multiple devices like 
![ic_devices_black_24dp_2x](https://user-images.githubusercontent.com/1265208/29295036-2d64afe8-8107-11e7-82a6-0c3b5cbdc7eb.png). However, by default I'd like to respect how Gnome does things, and avoid too many options in the preferences, since each one makes a call to GSettings and staying responsive to these could get costly.

Which would you prefer?

**Comment by isantop** [comment] 2017-08-14 22:46
I think a different icon would probably work well. It's not so much that there are too many icons, more-so that there is a duplicate.

**Comment by severin-lemaignan** [comment] 2017-08-15 20:37
IMHO, this is a very real issue. Two icons are one icon two much -- The gnome-shell topbar has a very lean design, and adding several icons for a unique task ("managing a mobile phone") is a design issue -- even though the technical rationale for two icons might be valid.

After installing the extension, I immediately saw the phone icon in 'system indicator' area. I clicked on it, then on 'Mobile devices'. I was expecting to see my connected device there, but I could only see 'Mobile settings' -- so I assumed my device was not successfully paired or something like that, and after 5 frustrating minutes, I discovered 'by chance' the *second* icon that actually give access to the device -- quite confusing!

As such, I would be very supportive of merging into the system menu the access to the device features.

**Comment by andyholmes** [comment] 2017-08-15 22:41
@severin-lemaignan I agree the panel is meant to be lean, in fact I believe that's why "TopIcons Plus" is still an extension and by default indicators are in a pop-out widget in the bottom-left corner. Much earlier in developing the extension that was a configurable option (to move device menus from the status icons to the user menu). I took it out for a few reasons:

* even with only four smallish icons the User Menu gets quite large (to the point of creating a scrollbar sometimes), even with only two devices
* I tried putting each menu in a sub-menu, but that means a sub-menu in a sub-menu and that behaviour is not well defined in the Gnome Shell or Shell theming
* I assumed most people using this would be coming from indicator-kdeconnect which puts them in the status tray anyways.

To be honest, I'm surprised it took you 5 minutes (even 10 seconds would be too long) to find the second icon. This is not a jab at you; having written the extension it's hard for me predict this problem, since I know exactly where to look. You're also not the first to mention going through those same steps of confusion.

I've pushed a commit which changes the System Indicator icon to the one shown above, which is the Google Material icon for "[Device Link](https://support.google.com/websearch/answer/6128427?co=GENIE.Platform%3DAndroid)". I'm not really happy with that either, since it will be an un-themable icon, but it's also the only and/or standard way of indicating that the service itself (ie KDE Connect/MConnect) is not active.

I'm happy to hear more discussion on this matter.

**Comment by andyholmes** [comment] 2017-08-16 03:09
@severin-lemaignan Here is a test build which includes a new preference 'device-indicators', please give it a try and let me know your thoughts.

You'll have to toggle the setting in the extension preferences, since the default is to still show device indicators, otherwise the default behaviour would change for current users.

[mconnect@andyholmes.github.io.zip](https://github.com/andyholmes/gnome-shell-extension-mconnect/files/1226956/mconnect.andyholmes.github.io.zip)

**Comment by severin-lemaignan** [comment] 2017-08-16 20:38
@andyholmes Great! Thank you for your great responsiveness!

Here a screenshot of the test build on my machine, I think it looks really good:
![mconnect](https://user-images.githubusercontent.com/385379/29383971-aa5a4b76-82d2-11e7-8410-e4d314af11b7.png)

However, I agree that using a non-standard icon is not a great idea.

Besides, what about showing the standard 'phone' icon as you did before, but *only* when at least one device is paired (the sub-menu 'mobile device' would however always be present in the menu).
That would provide a quick way to know whether the mobile device is around and paired (-> icon visible) 

Right now, the icon is always visible, even if no mobile is around: this goes against the normal, expected behaviour of the indicators. For instance, the 'wifi network' icon is only visible when the computer is connected to a wifi network, etc

**Comment by isantop** [comment] 2017-08-16 20:54
@severin-lemaignan Unrelated note, but I can't help it since it's bugging me. :)

It looks like your Pop theme is out of date. You should grab the latest version to help with memory usage!

**Comment by severin-lemaignan** [comment] 2017-08-16 20:56
@isantop :-D I'll check that out, I promiss!

**Comment by andyholmes** [comment] 2017-08-16 21:03
Essentially that's what it does; the system indicator indicates that the service is active. As an example, kill kdeconnectd/mconnect and the icon will disappear, while the *Mobile Devices* entry will remain and a *Enable* item will be added allowing you to "enable" or start the service.

As I mentioned, in the original design gnome never intended for indicators (outside of the service indicators) to be a thing at all, which is why by default they got stuffed in a little slide out drawer in the bottom-left corner of the screen (and the panel button class was added much later in the series). Another example is tooltips, for which in St (Shell Toolkit) there is no such widget; it was explicitly excluded from their design philosophy.

I do see what you're getting at, however, and I'm a big fan of minimalism and elegance. I actually proved myself wrong on this one, and agree (although I use the per-device indicators) it really does look good, and not cramped in the user menu. At this point I'm struggling to find a way to handle so many UI options dynamically without making excessive calls to GSettings. The way that I handled this change was a bit ugly (in fact there's a small bug I've committed, but not pushed a fix for).

I'll re-open the issue for some more discussion, and have a think on how I can refactor the code to make this easier on myself to approach.

**Comment by severin-lemaignan** [comment] 2017-08-16 21:10
@andyholmes From the end user perspective, there is little point in knowing whether the kdeconnect/mconnect daemon is running or not. Instead we would expect the icon to tell us whether *our phone* is present (paired) or not (and that's why I think the original 'phone' icon was better: when visible, it really conveys the idea 'phone present and paired').

**Comment by andyholmes** [comment] 2017-08-16 21:44
@severin-lemaignan That is what the system indicators are for, though, services which can be active/enabled, inactive/disabled. If the service stops, or isn't started automatically, by what means could you tell if the connection problem was your device or the service?

It also wouldn't describe a situation where multiple devices should be connected, but one has become disconnected; essentially only conveying that the service is running, with an indeterminate number of devices present. Personally I connect both my tablet and my phone (also it's possible to connect other laptops/PCs via KDE Connect protocol).

**Comment by severin-lemaignan** [comment] 2017-08-16 21:55
@andyholmes the way I see it (but I might be wrong in my thinking ;-) ):

- we assume (for now) that the daemon is running (kdeconnect/mconnect)
- no phone/no tablet -> no icon (exactly like: no battery -> no battery icon, no sound card -> no sound icon, etc)
- if at least one mobile device is paired, the icon appears (a generic 'phone' to symbolise any mobile device is fine IMHO, but could as well be a tablet icon if its a tablet, a phone icon if it's  a phone, two phones if it's more than one device, etc)
- once we open the menu, the various devices appear, one under the other, followed by the 'Mobile setting' menu
- if the daemon is *not* running: no icon, and when we open the 'Mobile devices' sub-menu, a clickable entry labelled 'Start service...' that starts the daemon

Would that work?

**Comment by andyholmes** [comment] 2017-08-16 22:26
@severin-lemaignan I think this discrepancy we're having is in part due to the fact that we're both looking at this from the perspective of different display modes; you user menu entries, and I per-device indicators.

I see where you're coming from, and I'm with you almost all the way, however, I'm hesitant to add multiple system indicators. That seems to really just replicate the per-device indicators, albeit without the popups, and is a much clearer transgression of the design principles of that area of the panel.

In regards to the icon choice itself, I'd be more in favour of a generic phone icon, however that was how this issue originally got opened :) It occurred to me when @isantop first opened this issue that it's a lot harder to get icon themers, especially the stock theme Adwaita, to adopt a series of standard status icons than it is just an application icon. Two nice things about bundling custom SVG's in a GResource is:

* it works like an overlay of fallbacks that only get used if the named icon is missing from the theme, and can thus later be filled in by themers (also why I named the icon 'device-link-symbolic')
* Gtk can automagically re-colour the icons to context

The reason I chose the icon I did is because it's Google's [Device Link](https://support.google.com/websearch/answer/6128427) icon, which is at least nominally what KDE Connect is, and aside from not meshing perfectly with every theme, it actually conveys the purpose pretty well.

It's about dinner time here, but I'm happy to continue the conversation, and as I said one hurdle I'll have to clear is how achieve any of this elegantly in the code without tons of convoluted logic and GSettings calls.

**Comment by severin-lemaignan** [comment] 2017-08-17 06:19
@andyholmes sorry, I think I was not clear: I'm not suggesting to have more than one icon displayed at the same time. It would be indeed a serious design breach. I was instead suggesting that:

- if *exactly one* phone is paired, show the [phone icon](http://fontawesome.io/icon/mobile/)
- if *exactly one* tablet is paired, show instead the [tablet icon](http://fontawesome.io/icon/tablet/)
- if *more than one* phones are paired, show instead an icon representing 2 phones
- if *more than one* (mixed) devices are paired, show instead an icon representing 1 phone + 1 tablet

![mconnect-devices](https://user-images.githubusercontent.com/385379/29398286-fafa002a-8323-11e7-8e91-8fdf1354c22d.png)

I must say I'm not a big fan of the 'device-link' icon that I find not very legible: most of the icon depicts a laptop, which is irrelevant to the main role of the extension: manage your mobile devices -- the fact it is familiar to kdeconnect users is not very relevant IMHO: kdeconnect is not very common anyway, even the less on gnome. Nice integration with gnome UI guidelines and visual consistency is more important.

And I do like your approach that consist in bundling SVG that can be possibly overridden by themers :-)

**Comment by andyholmes** [comment] 2017-08-17 06:49
@severin-lemaignan 
I see your approach, but this would require quite a bit of extra logic, as it requires tracking dynamically both the amount and types of devices, for what amounts to a 16x16 pixel icon. Consider that just adding the option to move the device controls to the user menu (a relatively simple task by comparison) added 58 lines of code, most of which is comprised of  ~8 signal handlers/GSettings calls. I'll likely be able to trim that down with some refactoring, but again, that's a relatively simple task by comparison.

> the fact it is familiar to kdeconnect users is not very relevant IMHO: kdeconnect is not very common anyway

But this is a KDE Connect extension? The particular icon is not super relavant; I chose it because I was already using icons from the Material Design project, the possibility it may end up being themed itself, if Google ever expands Device Link program out of America, and because it solved the original issue of being too similar to the device indicators.

**Comment by severin-lemaignan** [comment] 2017-08-17 08:39
I understand that dynamically managing the number and type of devices is much more involved, and for that matter, simply having the 'phone' icon to show up whenever at least one mobile device is paired and present would already go a long way in making the general behaviour easier to understand.

Regarding the KDE connect icon: the fact that the extension relies underneath on KDE connect is, as a matter of fact, nearly invisible: once kdeconnect is installed, the user nearly never interact with it (except when clicking on 'Mobile settings') and as such, I do not think the icon of kdeconnect itself is very visible/important.
When I said that 'kdeconnect is not very common anyway', I meant that I do not believe many people use it as of today (at least in the gnome world), and as such, the general population of gnome users is not really accustomed to the visual identity of kdeconnect (if there's such a thing, anyway!). On the other hand, if your extension fits well in term of visual identity and expected behaviour within the gnome-shell paradigm, then it might drive the adoption of the indicator and, more broadly, of `mconnect` (and, who knows, even get shipped by default in future gnome releases).

**Comment by andyholmes** [comment] 2017-08-17 19:46
I'd be willing to accept submission of a new icon, but many people are still using/prefer the per-device indicators, so a generic phone icon would cause confusion.

As far including KDE Connect itself, that's quite unlikely given the half-gig of kde dependencies it requires. It would be nice if there were a freedesktop DBus standard, but MConnect itself is still quite early in development and written in Vala, which is dying language. If much of elementary os and libfolks weren't written in it, it would probably be dead already. The only saving grace is that Vala is transpiled into C before it's compiled, so any existing code could probably be salvaged without too much hassle.

**Comment by isantop** [comment] 2017-08-17 20:26
Regarding Vala, it's going to be the de facto standard language for GNOME apps going forward (Starting with GTK 4 iirc). I'd hardly call it a dying language.

**Comment by severin-lemaignan** [comment] 2017-08-17 20:38
I've made a mockup of my proposal, it is maybe easier to understand that way:

![mconnect](https://user-images.githubusercontent.com/385379/29432506-3eab367c-839c-11e7-8d39-65a4bd428fad.jpg)

A: daemon not started -> no icon in the top bar, the 'Mobile devices' sub-menu offers to start the daemon
B: daemon running, no device paired -> no icon in the top bar, the 'Mobile devices' simply shows the settings
C: one mobile device (either phone or tablet) -> generic 'mobile device' icon in the top bar (for instance, a smartphone icon), access to the features of the device from the 'Mobile devices' sub-menu
D: several devices paired -> same icon in the top bar, each of the devices is listed in the sub-menu, one after the other

**Comment by andyholmes** [comment] 2017-08-17 20:53
@severin-lemaignan I see, however using a generic phone icon would still be confusing for folks using the indicators, which is many, since a phone icon is shown for smartphones. See the first post in this issue with accompanying screenshot. Something *along the lines* of the device link icon would work much better I think, for all situations.

@isantop I base my claim that Vala is dying on several conversations I've had with Philip Whitnall and Niels De Graef (personally I think the idea behind Vala/Genie is great, although there's some overlap with the purpose of GObject introspection). Excerpt from Gnome bug #786187 (emphasis mine):

> The underlying bug here is that libfolks is not usable from introspection bindings. Fixing that either means fixing bug #639908 (which is unlikely given that **Vala is essentially dead**, and g-i has little active maintenance atm); or changing libfolks’ APIs to not use libgee.

**Comment by severin-lemaignan** [comment] 2017-08-17 20:59
@andyholmes My assumption is that we'd remove the device-specific indicators, as they result in too many icons (like discussed toward the top of this thread)

**Comment by andyholmes** [comment] 2017-08-17 21:04
@severin-lemaignan I'm happy to add the feature to move them to the menu, but many people coming to this extension are coming from indicator-kdeconnect, and I prefer the panel indicators myself.

**Comment by severin-lemaignan** [comment] 2017-08-17 21:06
@andyholmes ok, fair enough! :-)

**Comment by HEXcube** [comment] 2017-08-18 19:26
> if exactly one phone is paired, show the phone icon
> if exactly one tablet is paired, show instead the tablet icon
> if more than one phones are paired, show instead an icon representing 2 phones
> if more than one (mixed) devices are paired, show instead an icon representing 1 phone + 1 tablet
>![](https://user-images.githubusercontent.com/385379/29398286-fafa002a-8323-11e7-8e91-8fdf1354c22d.png)

Don't forget the notebook and desktop icons, coz phones & tablets aren't the only devices KDE Connect syncs. :relaxed: 

![Indicator KDEconnect](https://user-images.githubusercontent.com/3755396/29474396-269c425a-8479-11e7-96dd-5b62c5643ae9.png)

**Comment by andyholmes** [comment] 2017-08-19 03:57
This issue is still on my mind, although there are other things I'd like to work through first like SMS/contacts, translations, and some other bits. Still, the point about being more Gnome-ish in general is well taken, the major points for me are as follows:

* **Performance, responsiveness & low code complexity is important for an extension**
    Maintainability/hackability, elegancy, as few signal handlers/GSettings calls as possible, cyclomatic complexity (eg. number of if/then branches), etc. At the same time, I also believe preference changes should be dynamic/instant which means signals and reasonable choice which means *some* complexity.
* **Well defined, easily understood set of icons, that work well across themes**
    This is clearly central to the issue here; universally understandable, quick access to useful information at a glance - and of course beautiful. This could be tough, but made easier since these are symbolic icons (non-symbolic icons would be near impossible to make cross-theme pretty)
* **System Indicator purpose**
    I strongly believe these are for indicating service status, with an optional "level" of some sort; good examples are Volume & Wi-Fi. That (and coding complexity) aside, complex "multi-vector" information is difficult to present clearly within 24-16 pixels (depending on your panel size)

Again, this is pretty much on the back burner for me, but I am sincere when I say overall project direction is open to discussion.

@isantop I was curious where you had read/heard Vala was going to be the de facto language for Gnome going forward. This is a topic I'm fairly interested in, but searching a bit I can't seem to get a clear answer.

**Comment by cwmke** [comment] 2017-08-20 06:35
One note I'd like to add is it that currently unpaired devices also receive a panel indicator which creates clutter. For example, I have one device paired but I see 3 devices in my top bar.

**Comment by andyholmes** [comment] 2017-08-20 06:37
@cwmke By default devices that are Paired & Offline, or Online & Unpaired are shown, but there is an option in the preferences to change that. Let me know if it's not working again (at one point it wasn't)

**Comment by rugk** [comment] 2017-08-21 11:18
IMHO the current green icon when connected is annoying, especially as all other icons in GNOME are black/white. (I know indicating "connected" is nice, but use a tick or so… the tick could even be colored if you want, as it is a smaller element than the green circle.) Also that icon is soo small and barely visible (what I see is – if said in a nice way – a square on a green point).
However, I really like the integration into the top-right menu, this is how it should look like.

**Comment by andyholmes** [comment] 2017-08-21 15:29
My understanding is that these icons are not actually standard. The fallback icons I supply with the extension are from Numix, while Ubuntu seems to patch in icons to Adwaita. The icons in your screenshot must be from another theme you have installed.

**Comment by rugk** [comment] 2017-08-21 20:22
Default GNOME theme (Adwaita), Fedora 26.

**Comment by andyholmes** [comment] 2017-08-21 20:27
Default in Adwaita on Ubuntu:
![default-adwaita-connected](https://user-images.githubusercontent.com/1265208/29536852-4aa285a4-8674-11e7-8a21-ee1e00a27935.png)

Probably these are patched in by distributions, nothing to do but change your icon theme, unfortunately.

**Comment by rugk** [comment] 2017-08-21 20:36
```
$ locate smartphone-connected
/usr/share/icons/hicolor/32x32/status/smartphone-connected.png
/usr/share/icons/hicolor/scalable/status/smartphone-connected.svg
```

I am just giving you the ZIP of all:
[icons.zip](https://github.com/andyholmes/gnome-shell-extension-mconnect/files/1240079/icons.zip)

PNGs are 32x32, "scalable" SVG, of course.

**Comment by andyholmes** [comment] 2017-08-21 20:39
Ah, then since Fedora doesn't patch those icons into Adwaita like Ubuntu does, it's falling back to the hicolor theme. If you want different icons you must either modify the Adwaita theme manually or use a different theme which has those icons.

**Comment by rugk** [comment] 2017-08-21 20:41
So the icons I uploaded, are your ones (the "fallback"?) Why not just provide proper icons. IMHO you should not rely on distros patching your stuff.
As I understand it, this project is mostly focused on GNOME users, so at least with the default theme it should work "out of the box".

**Comment by andyholmes** [comment] 2017-08-21 20:47
Nope. The icons I provide from Numix are used if the user's icon doesn't have those icons _and_ doesn't specify a fallback theme which has those icons. This prevents device indicators never being visible in those rare cases.

In this case, Adwaita doesn't have the icons, but _does_ specify a fallback theme which has those icons. In fact the icons do work "out of the box", just not with icons you like. _Forcing_ users to use specific icons would break theming for everyone and create a possible situations like icons that are too light or dark for the panel.

**Comment by rugk** [comment] 2017-08-21 22:18
So this is an issue with Adwaita? It uses the wrong icons?

**Comment by andyholmes** [comment] 2017-08-21 22:43
Adwaita doesn't include these icons [even in master](https://github.com/GNOME/adwaita-icon-theme/tree/master/Adwaita/scalable/status)  and as far as I know hicolor is a freedesktop.org thing that [hasn't been updated in several years](https://cgit.freedesktop.org/xdg/default-icon-theme/) when KDE Connect was not a well subscribed program, aside from not being particularly cross-desktop.

Even though the icons could in principle be covered by the [freedesktop.org Icon Naming Specification guidelines](https://standards.freedesktop.org/icon-naming-spec/icon-naming-spec-latest.html#guidelines), the spec only defines "phone" (not smartphone, tablet or laptop) and places it in the "devices" category (as it probably should) not the "status" category as KDE Connect does with it's icons.

As far as I know, these icons are used _only_ by KDE Connect and have probably only been patched into Gnome distributions in recent release cycles due to increased usage of KDE Connect and thus demand for the icons. So it's not so much a bug, but an unanticipated need for icons not named correctly, categorised correctly or applicable to Gnome desktops give the ~1/2 GB of KDE libs it depends on.

**Comment by rugk** [comment] 2017-08-22 09:45
> that hasn't been updated in several years

[Except of 100 minutes ago](https://cgit.freedesktop.org/xdg/default-icon-theme/commit/?id=42104e0d9c9af5201a3e502396730619217f626d). :wink: 

> and places it in the "devices" category (as it probably should)

BTW in the "devices" dir here, nearly no icons are saved, so…

> applicable to Gnome desktops give the ~1/2 GB of KDE libs it depends on.

I have KDE connect installed, so if they are included there, I would have them. (Just looked: At least in the "kdeconnect" package they are not directly included, could be a dependency, however.) 

Anyway, I see the problem, but still don't know where to continue. I mean it is surely not expected/the proper way that distros need to patch this in, so who is to blame here? Freedesktop? GNOME directly? Adwaita? Who exactly should supply these icons – I'd want to open further issues in their tracker, but who?

Also:
> In this case, Adwaita doesn't have the icons, but does specify a fallback theme which has those icons.

So the ones I uploaded are the fallback ones? But why, don't they fit to the default GNOME theme? I mean if they test whether the fallback works, then with the defaults of GNOME…
Still don't understand this. I mean, I just want to have these icons… 🙏

**Comment by andyholmes** [comment] 2017-08-22 10:08
> Except of 100 minutes ago.

Interesting, I heard Adwaita virtually replaced it.

> BTW in the "devices" dir here, nearly no icons are saved, so…

Perhaps, but it's what the freedesktop.org spec recommends, and hicolor is the freedesktop.org theme

>I have KDE connect installed, so if they are included there, I would have them. (Just looked: At least in the "kdeconnect" package they are not directly included, could be a dependency, however.)

Nope, they are likely shipped in KDE's default icon them (eg. whatever they have instead of Adwaita)

>So the ones I uploaded are the fallback ones? But why, don't they fit to the default GNOME theme? I mean if they test whether the fallback works, then with the defaults of GNOME…

* Adwaita does not have these icons, probably because they are for a KDE program and Adwaita is the default Gnome theme.
* The icons you uploaded are in the hicolor theme (at least on your system).
* hicolor is the freedesktop.org icon theme. It's created to be acceptable across different desktops (eg. Gnome, KDE, XFCE, LXDE, etc) and provide acceptable coverage for most uses.
* Since you have the Adwaita icon theme selected, which doesn't have those icons in it, Gnome/Gtk goes looking for the next best place to get them. This turns out to be hicolor on your system.

> I mean, I just want to have these icons… ￼

You do, just not ones you prefer. If you want different icons, you must use a different icon theme, that's what icon themes are for!

If you _really_ want to use Adwaita icons, except for those KDE Connect ones from hicolor, your only option is to modify the theme.

**Comment by rugk** [comment] 2017-08-22 10:52
Ahh, now I understood that. So basically Adwaita is missing these icons…

So I created an issue for that: https://bugzilla.gnome.org/show_bug.cgi?id=786601

**Comment by isantop** [comment] 2017-08-22 20:20
@andyholmes hicolor is intended to be specified as a fallback for any icon themes. As an example, applications are intended to install their developer-supplied default icons into the hicolor theme to ensure that if an icon theme doesn't provide application icons, it will load the icon by default. It's much better to assume that hicolor will be used as a fallback (since that how the freedesktop.org icon theme spec is written).

**Comment by andyholmes** [comment] 2017-08-22 20:24
@isantop Ah, so it's a fallback theme itself, but also a repository for applications to put *their* fallback/default icons?

**Comment by isantop** [comment] 2017-08-22 20:25
Correct. There's more information here: https://standards.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html

Of note, the description for the "inherits" field: 

>  The name of the theme that this theme inherits from. If an icon name is not found in the current theme, it is searched for in the inherited theme (and recursively in all the inherited themes).
> 
> If no theme is specified implementations are required to add the "hicolor" theme to the inheritance tree. An implementation may optionally add other default themes in between the last specified theme and the hicolor theme.

**Comment by rugk** [comment] 2017-08-22 20:27
Interesting, the question now is just: Can GNOME extensions install icons in that hicolor dir?

**Comment by andyholmes** [comment] 2017-08-22 20:38
This one can't, it is only installable as a local/user extension. Even if that weren't the case, these icons are already in your hicolor theme, a system package would fail to install due to conflicts with those files.

Instead it uses Gnome's recommendation to [extend the icon theme with GResource](https://developer.gnome.org/ThemedIcons/).

**Comment by rugk** [comment] 2017-08-22 20:42
Nice, so then the icon should be displayed properly? (i.e. not falling back to the default hicolor ones…)

**Comment by andyholmes** [comment] 2017-08-22 20:48
Nope. The icons *are* displaying correctly - you just don't like them. Adwaita is falling back to hicolor and displaying the icons available on your system.

The icons I provide are only for rare cases (so far only one reported case) where an icon theme doesn't have those icons, and there are no other fallbacks available. The icons I provide, I did not create. They are not from this extension, or from KDE Connect, they're from the Numix theme.

**Comment by rugk** [comment] 2017-08-22 21:08
But Adwaita should not fall back to hicolor when you set your icons. I thought @isantop described hicolor as the "last fallback of the fallback", so your icons should actually be used before…

**Comment by andyholmes** [comment] 2017-08-22 21:19
He's right that hicolor is the standard fallback theme, and that's exactly what's happening. Like I said the icons I include are only for situations where the current icon theme doesn't have those icons, and no fallback (like hicolor) provides them either.

These aren't standard icons, they're from Numix, so you aren't missing out on any stock functionality or graphics. Perhaps you might like the Numix theme, it's my personal favourite. Although I've been keeping an eye on Pop as well, which @isantop has been working on.

Again, there's nothing I can do to fix this, because nothing is broken. Everything is working exactly how it's intended to.

**Comment by andyholmes** [comment] 2017-08-22 23:16
@isantop since you're a bit of a an icon buff, could you recommend a better icon for "SMS" than "user-available-symbolic" which is not always a picture of a message bubble?

**Comment by isantop** [comment] 2017-08-22 23:43
Ah, I wondered why you picked an avatar icon for the SMS icon! :)

Having a look at the similarities between Pop, elementary, and Adwaita (I don't presently have any other icon themes installed), I think my first choice would be `mail-send-symbolic`.

![mail-send-pop](https://user-images.githubusercontent.com/5883565/29592400-fce59412-8760-11e7-8c15-2789184f489e.png)
![mail-send-ad](https://user-images.githubusercontent.com/5883565/29592405-0291432a-8761-11e7-8bd0-bffc79d31b3f.png)
![mail-send-ele](https://user-images.githubusercontent.com/5883565/29592409-052dcdd8-8761-11e7-8d4a-cf08a3cb8d4a.png)

Generally it seems to be either a sort of postage stamp or paper airplane, which is pretty widely seen as a sort of send icon.

It's definitely hard because there doesn't seem to be a standard icon for chat messages.

**Comment by andyholmes** [comment] 2017-08-23 00:17
![sms-icon-adwaita](https://user-images.githubusercontent.com/1265208/29593009-94ea6580-875c-11e7-8f0e-1248b3baa751.png)
![sms-icon-pop](https://user-images.githubusercontent.com/1265208/29593011-94ebeb62-875c-11e7-9408-cd8ffadad9b0.png)
![sms-icon-vimix-numix](https://user-images.githubusercontent.com/1265208/29593010-94ea98f2-875c-11e7-96c0-89babe749b51.png)

Numix seems to play it pretty close to Adwaita with their icons, so I think they both have a bubble for `user-available-symbolic`. `pda-symbolic` might be like that, but radically different on others. I think some themes link `pda-symbolic` and `input-tablet` actually.

Thanks for the advice, `mail-send-symbolic` seems like a better choice across themes!

**Comment by rugk** [comment] 2017-08-23 06:47
Please don't use the "send" icon at the top, as it is usually used right next to an input field to show the user, well, to send something. You need some compose icon there.

Also can't you prioritize your fallback icons to take presence instead of the hicolor? The current fallback prefers hicolor, which I don't want.

**Comment by andyholmes** [comment] 2017-08-23 07:03
> You need some compose icon there.

There doesn't seem to be a symbolic compose icon, if you can find a better symbolic icon that's relevant to SMS/messaging across themes I'd be glad to hear it, though.

> Also can't you prioritize your fallback icons to take presence instead of the hicolor?

Nope, there is no way to do that.

**Comment by rugk** [comment] 2017-08-23 07:19
Actually I do not find the current one soo bad…

> Nope, there is no way to do that.

😟

**Comment by rugk** [comment] 2017-08-23 07:30
Because of an icon? 😂 No, …

**Comment by isantop** [comment] 2017-08-23 16:00
@rugk The problem he's talking about in this case is that the other icon was a status indication icon, and has very different looks depending on the icon theme. For example, many themes make that IM User Available status icon a person or avatar, rather than a chat bubble. Others still might use a simple circle. These don't convey the idea of an SMS at all, whereas the send icon, while suboptimal, indicates to send _something_.

**Comment by andyholmes** [comment] 2017-10-04 04:12
Since this has been quiet for some time now, I'm going to close it.

**Closed by andyholmes** 2017-10-04 04:12 UTC
Labels: opinions wanted
